# Generated by Django 3.2.5 on 2021-09-10 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=32)),
                ('asset', models.CharField(max_length=4)),
                ('amount', models.FloatField()),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('financer', models.CharField(default=None, max_length=32)),
                ('complete_time', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default=None, max_length=32)),
                ('receiver', models.CharField(default=None, max_length=32)),
                ('asset', models.CharField(max_length=4)),
                ('amount', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdt', models.FloatField(default=0)),
                ('btc', models.FloatField(default=0)),
                ('eth', models.FloatField(default=0)),
                ('ada', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
