# Generated by Django 3.2.5 on 2021-09-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_auto_20210910_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='usdt',
            new_name='sol',
        ),
        migrations.AddField(
            model_name='balance',
            name='usds',
            field=models.FloatField(default=0),
        ),
    ]
