# Generated by Django 3.2.5 on 2021-09-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_auto_20210912_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='usds',
            new_name='usd',
        ),
    ]
