# Generated by Django 3.2.5 on 2021-09-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_rename_usds_balance_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='dot',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='balance',
            name='xrp',
            field=models.FloatField(default=0),
        ),
    ]
