# Generated by Django 3.2.5 on 2021-09-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_auto_20210912_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='ltc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='balance',
            name='uni',
            field=models.FloatField(default=0),
        ),
    ]
