# Generated by Django 3.2.5 on 2021-09-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_alter_balance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='bnb',
            field=models.FloatField(default=0),
        ),
    ]
