# Generated by Django 3.2.5 on 2021-09-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_balance_bnb'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='busd',
            field=models.FloatField(default=0),
        ),
    ]
