# Generated by Django 3.2.5 on 2021-09-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_auto_20210914_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='financer',
            new_name='peer_name',
        ),
    ]
