# Generated by Django 3.2.5 on 2021-09-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0013_rename_financer_requests_peer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='status',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet_address',
        ),
    ]
