# Generated by Django 3.2.5 on 2021-09-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0014_auto_20210915_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='usd',
        ),
    ]
