# Generated by Django 3.2.5 on 2021-09-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0016_delete_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=4)),
                ('asset', models.CharField(max_length=4)),
                ('asset_amount', models.CharField(max_length=4)),
                ('busd_amount', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
