# Generated by Django 3.2.5 on 2021-10-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0017_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='busd',
            new_name='usdt',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='ltc',
        ),
    ]
